# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25dd44b3668c911204b47a7f2163480ae80c3713a881d500e1dfac6407ffa6897652d50641f64b083d7cc7304e2d0026f82b9182b14379b18f7d69559215d9a9

test:
  secret_key_base: df967ac226570b578336f6f1b2a5986393f385826565ee978fdb711415d16145fc26a945578458a23453b5633afe7257e31e5a008bca9eb61f05518a65689c70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
